// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroPedidosConDetalle.DAL;

namespace RegistroPedidosConDetalle.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20211015231154_Agregando Suplidores y productos")]
    partial class AgregandoSuplidoresyproductos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("RegistroPedidosConDetalle.Models.Ordenes", b =>
                {
                    b.Property<int>("OrdenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<float>("Monto")
                        .HasColumnType("REAL");

                    b.HasKey("OrdenId");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("RegistroPedidosConDetalle.Models.OrdenesDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Cantidad")
                        .HasColumnType("REAL");

                    b.Property<float>("Costo")
                        .HasColumnType("REAL");

                    b.Property<int>("OrdenId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrdenesOrdenId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleId");

                    b.HasIndex("OrdenesOrdenId");

                    b.ToTable("OrdenesDetalle");
                });

            modelBuilder.Entity("RegistroPedidosConDetalle.Models.Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Costo")
                        .HasColumnType("REAL");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<float>("Inventario")
                        .HasColumnType("REAL");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            Costo = 80f,
                            Descripcion = "Cartón de jugo de naranja, 1 litro",
                            Inventario = 110f
                        },
                        new
                        {
                            ProductoId = 2,
                            Costo = 50f,
                            Descripcion = "Cartón de leche Listamilk, 1 litro",
                            Inventario = 85f
                        },
                        new
                        {
                            ProductoId = 3,
                            Costo = 700f,
                            Descripcion = "Pizza Grande Suprema de Pollo",
                            Inventario = 1225f
                        });
                });

            modelBuilder.Entity("RegistroPedidosConDetalle.Models.Suplidores", b =>
                {
                    b.Property<int>("SuplidorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombres")
                        .HasColumnType("TEXT");

                    b.HasKey("SuplidorId");

                    b.ToTable("Suplidores");

                    b.HasData(
                        new
                        {
                            SuplidorId = 1,
                            Nombres = "Pizza Hut"
                        },
                        new
                        {
                            SuplidorId = 2,
                            Nombres = "C&H Technology"
                        },
                        new
                        {
                            SuplidorId = 3,
                            Nombres = "Rica"
                        });
                });

            modelBuilder.Entity("RegistroPedidosConDetalle.Models.OrdenesDetalle", b =>
                {
                    b.HasOne("RegistroPedidosConDetalle.Models.Ordenes", null)
                        .WithMany("OrdenesDetalle")
                        .HasForeignKey("OrdenesOrdenId");
                });

            modelBuilder.Entity("RegistroPedidosConDetalle.Models.Ordenes", b =>
                {
                    b.Navigation("OrdenesDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
